### ISSUE TITLE
Reconfigure heroku to deploy development branch

### ISSUE THREAD

**Issue by fc-boost** [StartupBoost/website#51]
This will help to prepare releases

**Comment by fc-boost** [comment]
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  >=6.11.2
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >=6.11.2...
       Downloading and installing node 8.4.0...
       Detected package-lock.json: defaulting npm to version 5.x.x
       Bootstrapping npm 5.x.x (replacing 5.3.0)...
       npm 5.3.0 installed
-----> Restoring cache
       Skipping cache restore (new-signature)
-----> Building dependencies
       Installing node modules (package.json + package-lock)
       
       > deasync@0.1.10 install /tmp/build_0878c6ed6da121906e6026bc39d0f0bf/StartupBoost-website-9990c9a/node_modules/styled-jsx-postcss/node_modules/deasync
       > node ./build.js
       
       `linux-x64-node-8` exists; testing
       Binary is fine; exiting
       
       > uglifyjs-webpack-plugin@0.4.6 postinstall /tmp/build_0878c6ed6da121906e6026bc39d0f0bf/StartupBoost-website-9990c9a/node_modules/next/node_modules/uglifyjs-webpack-plugin
       > node lib/post_install.js
       
       added 990 packages in 34.808s
       Running heroku-postbuild
       
       > @startupboost/website@1.0.0 heroku-postbuild /tmp/build_0878c6ed6da121906e6026bc39d0f0bf/StartupBoost-website-9990c9a
       > next build
       
module.js:491
    throw err;
    ^
Error: Cannot find module 'webpack-bundle-analyzer'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/build_0878c6ed6da121906e6026bc39d0f0bf/StartupBoost-website-9990c9a/next.config.js:3:34)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @startupboost/website@1.0.0 heroku-postbuild: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @startupboost/website@1.0.0 heroku-postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2017-08-15T20_31_30_674Z-debug.log
{ Error: Cannot find module 'webpack-bundle-analyzer'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/build_0878c6ed6da121906e6026bc39d0f0bf/StartupBoost-website-9990c9a/next.config.js:3:34)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3) code: 'MODULE_NOT_FOUND' }
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by mfc-boost** [comment]
Already deploying development version on Heroku
